update_data: False
db_path: '/db/database.sqlite'
fasttext_model_path: './models/fasttext_model/pretrained_models/ft_native_300_ru_wiki_lenta_lemmatize.bin'
vosk_model_path: './models/speech_recognition/vosk-model-small-ru-0.22'