version: '3'
services:
  flask:
    build: ./backend
    container_name: backend-flask
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./backend:/backend
      - ./configs:/backend/configs
      - ./db/database.sqlite:/db/database.sqlite
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: gunicorn main:"create_flask_app()" -b 0.0.0.0:5000 --reload

  sqlite:
      image: nouchka/sqlite3:latest
      stdin_open: true
      tty: true
      volumes:
        - ./db/:/root/db/
